clear;
clc;
close all;

rng(42);

%% 1. Pagrindiniai parametrai

fileName = "C:\Users\barch\OneDrive\Рабочий стол\github\koliokvium\household_power_consumption.txt";

windowMinutes = 15;

trainRatio = 0.60;
validationRatio = 0.20;

baselineWindow = 96;

anomalyRate = 0.01;

maxWarningsPerDay = 5;

%% 2. Duomenu nuskaitymas

fprintf('Kraunami duomenys...\n');

opts = detectImportOptions( ...
    fileName, ...
    'Delimiter', ';');

opts = setvaropts( ...
    opts, ...
    {'Date','Time'}, ...
    'Type', 'string');

T = readtable( ...
    fileName, ...
    opts);

fprintf( ...
    'Pradinis irasu skaicius: %d\n', ...
    height(T));

%% 3. Datos ir laiko sujungimas

T.DateTime = datetime( ...
    T.Date + " " + T.Time, ...
    'InputFormat', ...
    'dd/MM/yyyy HH:mm:ss');

T.Date = [];
T.Time = [];

%% 4. Trukstamu reiksmiu tvarkymas

fprintf('Tvarkomos trukstamos reiksmes...\n');

variables = T.Properties.VariableNames;

for i = 1:length(variables)

    name = variables{i};

    if ~strcmp(name, 'DateTime')

        T.(name) = fillmissing( ...
            T.(name), ...
            'linear');

        T.(name) = fillmissing( ...
            T.(name), ...
            'previous');

        T.(name) = fillmissing( ...
            T.(name), ...
            'next');

    end

end

%% 5. Duomenu rikiavimas

T = sortrows(T, 'DateTime');

%% 6. Konvertavimas i timetable

TT = table2timetable( ...
    T, ...
    'RowTimes', ...
    'DateTime');

%% 7. Agregavimas i 15 minuciu langus

fprintf( ...
    'Atliekamas 15 minuciu agregavimas...\n');

TT15 = retime( ...
    TT, ...
    'regular', ...
    'mean', ...
    'TimeStep', ...
    minutes(windowMinutes));

TT15 = rmmissing(TT15);

fprintf( ...
    'Irasu po agregavimo: %d\n', ...
    height(TT15));

%% 8. Pagrindiniai pozymiai

activePower = ...
    TT15.Global_active_power;

reactivePower = ...
    TT15.Global_reactive_power;

voltage = ...
    TT15.Voltage;

current = ...
    TT15.Global_intensity;

sub1 = ...
    TT15.Sub_metering_1;

sub2 = ...
    TT15.Sub_metering_2;

sub3 = ...
    TT15.Sub_metering_3;

%% 9. Papildomi pozymiai

activeStd = movstd( ...
    activePower, ...
    [3 0]);

activeChange = [ ...
    0; ...
    diff(activePower)];

%% 10. Pozymiu matrica

X = [ ...
    activePower, ...
    reactivePower, ...
    voltage, ...
    current, ...
    sub1, ...
    sub2, ...
    sub3, ...
    activeStd, ...
    activeChange];

%% 11. Laiko duomenys

timeData = ...
    TT15.Properties.RowTimes;

%% 12. Netinkamu reiksmiu salinimas

validRows = all( ...
    isfinite(X), ...
    2);

X = X(validRows, :);

timeData = ...
    timeData(validRows);

fprintf( ...
    'Galutinis duomenu kiekis: %d\n', ...
    size(X,1));

%% 13. Chronologinis skaidymas

N = size(X,1);

trainEnd = floor( ...
    N * trainRatio);

validationEnd = floor( ...
    N * (trainRatio + validationRatio));

X_train = ...
    X(1:trainEnd, :);

X_validation = ...
    X(trainEnd+1:validationEnd, :);

X_test = ...
    X(validationEnd+1:end, :);

time_test = ...
    timeData(validationEnd+1:end);

fprintf('\n');
fprintf('Duomenu skaidymas:\n');

fprintf( ...
    'Mokymas: %d\n', ...
    size(X_train,1));

fprintf( ...
    'Validacija: %d\n', ...
    size(X_validation,1));

fprintf( ...
    'Testas: %d\n', ...
    size(X_test,1));

%% 14. Dirbtines anomalijos

fprintf('\n');
fprintf('Generuojamos dirbtines anomalijos...\n');

[X_validation_anomaly, labels_validation] = ...
    injectAnomalies( ...
    X_validation, ...
    anomalyRate);

[X_test_anomaly, labels_test] = ...
    injectAnomalies( ...
    X_test, ...
    anomalyRate);

fprintf( ...
    'Validacijos anomaliju: %d\n', ...
    sum(labels_validation));

fprintf( ...
    'Testo anomaliju: %d\n', ...
    sum(labels_test));

%% 15. BASELINE

fprintf('\n');
fprintf('========================================\n');
fprintf('BASELINE\n');
fprintf('Moving Average + Z-score\n');
fprintf('========================================\n');

baselineValidationScore = ...
    baselineScore( ...
    X_validation_anomaly, ...
    baselineWindow);

baselineTestScore = ...
    baselineScore( ...
    X_test_anomaly, ...
    baselineWindow);

baselineThreshold = ...
    selectThreshold( ...
    baselineValidationScore, ...
    labels_validation, ...
    maxWarningsPerDay);

baselineResult = ...
    calculateMetrics( ...
    baselineTestScore, ...
    labels_test, ...
    baselineThreshold);

fprintf( ...
    'Threshold = %.4f\n', ...
    baselineThreshold);

fprintf( ...
    'Recall = %.4f\n', ...
    baselineResult.recall);

fprintf( ...
    'Warnings/day = %.2f\n', ...
    baselineResult.warningsPerDay);

%% 16. Standartizavimas

meanTrain = ...
    mean(X_train, 1);

stdTrain = ...
    std(X_train, 0, 1);

stdTrain(stdTrain == 0) = 1;

X_train_s = ...
    (X_train - meanTrain) ./ stdTrain;

X_validation_s = ...
    (X_validation_anomaly - meanTrain) ./ stdTrain;

X_test_s = ...
    (X_test_anomaly - meanTrain) ./ stdTrain;

%% 17. ONE-CLASS SVM
% Pagrindinis metodas

fprintf('\n');
fprintf('========================================\n');
fprintf('ONE-CLASS SVM\n');
fprintf('PAGRINDINIS METODAS\n');
fprintf('========================================\n');

%% 18. Mokymo imties dydis

maxSamples = ...
    min(30000, size(X_train_s,1));

randomIndex = ...
    randperm( ...
    size(X_train_s,1), ...
    maxSamples);

X_svm_train = ...
    X_train_s(randomIndex, :);

fprintf( ...
    'SVM mokymui naudojama: %d irasu\n', ...
    size(X_svm_train,1));

%% 19. One-Class SVM modelis

svmModel = fitcsvm( ...
    X_svm_train, ...
    ones(size(X_svm_train,1),1), ...
    'KernelFunction', 'rbf', ...
    'KernelScale', 'auto', ...
    'OutlierFraction', 0.01, ...
    'Standardize', false);

fprintf('One-Class SVM mokymas baigtas.\n');

%% 20. SVM validacija

[~, svmValidationScore] = ...
    predict( ...
    svmModel, ...
    X_validation_s);

% Teigiama reiksme = didesnis anomalijos balas

svmValidationScore = ...
    -svmValidationScore;

%% 21. SVM testas

[~, svmTestScore] = ...
    predict( ...
    svmModel, ...
    X_test_s);

svmTestScore = ...
    -svmTestScore;

%% 22. SVM threshold

svmThreshold = ...
    selectThreshold( ...
    svmValidationScore, ...
    labels_validation, ...
    maxWarningsPerDay);

svmResult = ...
    calculateMetrics( ...
    svmTestScore, ...
    labels_test, ...
    svmThreshold);

fprintf( ...
    'Threshold = %.4f\n', ...
    svmThreshold);

fprintf( ...
    'Recall = %.4f\n', ...
    svmResult.recall);

fprintf( ...
    'Warnings/day = %.2f\n', ...
    svmResult.warningsPerDay);

%% 23. MLP AUTOENCODER

fprintf('\n');
fprintf('========================================\n');
fprintf('MLP AUTOENCODER\n');
fprintf('========================================\n');

inputSize = ...
    size(X_train_s,2);

hidden1Size = 8;
hidden2Size = 3;
hidden3Size = 8;

fprintf( ...
    'Architektura: %d-%d-%d-%d-%d\n', ...
    inputSize, ...
    hidden1Size, ...
    hidden2Size, ...
    hidden3Size, ...
    inputSize);

%% 24. Pradiniai svoriai

W1 = ...
    randn( ...
    hidden1Size, ...
    inputSize) * 0.05;

b1 = ...
    zeros(hidden1Size,1);

W2 = ...
    randn( ...
    hidden2Size, ...
    hidden1Size) * 0.05;

b2 = ...
    zeros(hidden2Size,1);

W3 = ...
    randn( ...
    hidden3Size, ...
    hidden2Size) * 0.05;

b3 = ...
    zeros(hidden3Size,1);

W4 = ...
    randn( ...
    inputSize, ...
    hidden3Size) * 0.05;

b4 = ...
    zeros(inputSize,1);

%% 25. MLP parametrai

eta = 0.01;

mlpIterations = 30;

Ntrain = ...
    size(X_train_s,1);

fprintf( ...
    'Mokymo iteraciju: %d\n', ...
    mlpIterations);

%% 26. MLP mokymas

fprintf('Mokomas autoencoder...\n');

for iteration = 1:mlpIterations

    totalError = 0;

    order = randperm(Ntrain);

    for k = 1:Ntrain

        n = order(k);

        x = ...
            X_train_s(n,:)';

        %% Pirmas sluoksnis

        v1 = ...
            W1 * x + b1;

        y1 = ...
            sigmoid(v1);

        %% Antras sluoksnis

        v2 = ...
            W2 * y1 + b2;

        y2 = ...
            sigmoid(v2);

        %% Trečias sluoksnis

        v3 = ...
            W3 * y2 + b3;

        y3 = ...
            sigmoid(v3);

        %% Isejimo sluoksnis

        y = ...
            W4 * y3 + b4;

        %% Klaida

        e = ...
            x - y;

        totalError = ...
            totalError + ...
            mean(e.^2);

        %% Backpropagation

        delta4 = e;

        delta3 = ...
            y3 .* (1 - y3) .* ...
            (W4' * delta4);

        delta2 = ...
            y2 .* (1 - y2) .* ...
            (W3' * delta3);

        delta1 = ...
            y1 .* (1 - y1) .* ...
            (W2' * delta2);

        %% Svoriu atnaujinimas

        W4 = ...
            W4 + ...
            eta * delta4 * y3';

        b4 = ...
            b4 + ...
            eta * delta4;

        W3 = ...
            W3 + ...
            eta * delta3 * y2';

        b3 = ...
            b3 + ...
            eta * delta3;

        W2 = ...
            W2 + ...
            eta * delta2 * y1';

        b2 = ...
            b2 + ...
            eta * delta2;

        W1 = ...
            W1 + ...
            eta * delta1 * x';

        b1 = ...
            b1 + ...
            eta * delta1;

    end

    averageError = ...
        totalError / Ntrain;

    fprintf( ...
        'Iteracija %d/%d, klaida = %.6f\n', ...
        iteration, ...
        mlpIterations, ...
        averageError);

end

fprintf('Autoencoder mokymas baigtas.\n');

%% 27. Autoencoder validacija

Nvalidation = ...
    size(X_validation_s,1);

aeValidationScore = ...
    zeros(Nvalidation,1);

for n = 1:Nvalidation

    x = ...
        X_validation_s(n,:)';

    v1 = W1 * x + b1;
    y1 = sigmoid(v1);

    v2 = W2 * y1 + b2;
    y2 = sigmoid(v2);

    v3 = W3 * y2 + b3;
    y3 = sigmoid(v3);

    y = W4 * y3 + b4;

    e = x - y;

    aeValidationScore(n) = ...
        mean(e.^2);

end

%% 28. Autoencoder testas

Ntest = ...
    size(X_test_s,1);

aeTestScore = ...
    zeros(Ntest,1);

for n = 1:Ntest

    x = ...
        X_test_s(n,:)';

    v1 = W1 * x + b1;
    y1 = sigmoid(v1);

    v2 = W2 * y1 + b2;
    y2 = sigmoid(v2);

    v3 = W3 * y2 + b3;
    y3 = sigmoid(v3);

    y = W4 * y3 + b4;

    e = x - y;

    aeTestScore(n) = ...
        mean(e.^2);

end

%% 29. Autoencoder threshold

aeThreshold = ...
    selectThreshold( ...
    aeValidationScore, ...
    labels_validation, ...
    maxWarningsPerDay);

aeResult = ...
    calculateMetrics( ...
    aeTestScore, ...
    labels_test, ...
    aeThreshold);

fprintf( ...
    'Threshold = %.6f\n', ...
    aeThreshold);

fprintf( ...
    'Recall = %.4f\n', ...
    aeResult.recall);

fprintf( ...
    'Warnings/day = %.2f\n', ...
    aeResult.warningsPerDay);

%% 30. Stabilumas

baselineStability = ...
    calculateStability( ...
    baselineTestScore, ...
    baselineThreshold);

svmStability = ...
    calculateStability( ...
    svmTestScore, ...
    svmThreshold);

aeStability = ...
    calculateStability( ...
    aeTestScore, ...
    aeThreshold);

%% 31. Galutine rezultatu lentele

Method = [
    "Moving Average + Z-score";
    "One-Class SVM";
    "MLP Autoencoder"
    ];

Recall = [
    baselineResult.recall;
    svmResult.recall;
    aeResult.recall
    ];

WarningsPerDay = [
    baselineResult.warningsPerDay;
    svmResult.warningsPerDay;
    aeResult.warningsPerDay
    ];

Stability = [
    baselineStability;
    svmStability;
    aeStability
    ];

Results = table( ...
    Method, ...
    Recall, ...
    WarningsPerDay, ...
    Stability);

%% 32. Rezultatai

fprintf('\n');
fprintf('========================================\n');
fprintf('GALUTINIAI REZULTATAI\n');
fprintf('========================================\n');

disp(Results);

%% 33. Rezultatu issaugojimas

writetable( ...
    Results, ...
    'rezultatai.csv');

fprintf( ...
    'Rezultatai issaugoti i rezultatai.csv\n');

%% 34. Baseline grafikas

figure;

plot( ...
    time_test, ...
    baselineTestScore);

hold on;

yline( ...
    baselineThreshold, ...
    '--');

xlabel('Laikas');

ylabel('Z-score');

title( ...
    'Moving Average + Z-score');

grid on;

%% 35. One-Class SVM grafikas

figure;

plot( ...
    time_test, ...
    svmTestScore);

hold on;

yline( ...
    svmThreshold, ...
    '--');

xlabel('Laikas');

ylabel('Anomalijos balas');

title( ...
    'One-Class SVM');

grid on;

%% 36. Autoencoder grafikas

figure;

plot( ...
    time_test, ...
    aeTestScore);

hold on;

yline( ...
    aeThreshold, ...
    '--');

xlabel('Laikas');

ylabel( ...
    'Rekonstrukcijos paklaida');

title( ...
    'MLP Autoencoder');

grid on;

%% 37. Dirbtines anomalijos

figure;

plot( ...
    time_test, ...
    X_test(:,1));

hold on;

anomalyIndex = ...
    labels_test == 1;

plot( ...
    time_test(anomalyIndex), ...
    X_test(anomalyIndex,1), ...
    'rx');

xlabel('Laikas');

ylabel('Global Active Power');

title( ...
    'Testo duomenys ir dirbtines anomalijos');

legend( ...
    'Elektros vartojimas', ...
    'Dirbtine anomalija');

grid on;

%% 38. ABLACIJA
% Pagrindinis metodas naudojant tik Global Active Power

fprintf('\n');
fprintf('========================================\n');
fprintf('ABLACIJA\n');
fprintf('========================================\n');

X_train_ab = ...
    X_train(:,1);

X_validation_ab = ...
    X_validation_anomaly(:,1);

X_test_ab = ...
    X_test_anomaly(:,1);

meanAb = ...
    mean(X_train_ab);

stdAb = ...
    std(X_train_ab);

if stdAb == 0
    stdAb = 1;
end

X_train_ab = ...
    (X_train_ab - meanAb) ./ stdAb;

X_validation_ab = ...
    (X_validation_ab - meanAb) ./ stdAb;

X_test_ab = ...
    (X_test_ab - meanAb) ./ stdAb;

%% 39. One-Class SVM su vienu pozymiu

svmAb = fitcsvm( ...
    X_train_ab, ...
    ones(size(X_train_ab,1),1), ...
    'KernelFunction', 'rbf', ...
    'KernelScale', 'auto', ...
    'OutlierFraction', 0.01, ...
    'Standardize', false);

[~, abValidationScore] = ...
    predict( ...
    svmAb, ...
    X_validation_ab);

abValidationScore = ...
    -abValidationScore;

abThreshold = ...
    selectThreshold( ...
    abValidationScore, ...
    labels_validation, ...
    maxWarningsPerDay);

[~, abTestScore] = ...
    predict( ...
    svmAb, ...
    X_test_ab);

abTestScore = ...
    -abTestScore;

abResult = ...
    calculateMetrics( ...
    abTestScore, ...
    labels_test, ...
    abThreshold);

fprintf( ...
    'SVM tik su Global Active Power:\n');

fprintf( ...
    'Recall = %.4f\n', ...
    abResult.recall);

fprintf( ...
    'Warnings/day = %.2f\n', ...
    abResult.warningsPerDay);

%% 40. ATSparumo TESTAS

fprintf('\n');
fprintf('========================================\n');
fprintf('ATSPARUMO TESTAS\n');
fprintf('========================================\n');

noiseLevel = 0.05;

noise = ...
    noiseLevel * randn(size(X_test));

X_test_noisy = ...
    X_test .* ...
    (1 + noiseLevel * randn(size(X_test)));

X_test_noisy_s = ...
    (X_test_noisy - meanTrain) ...
    ./ stdTrain;

[~, noisyScore] = ...
    predict( ...
    svmModel, ...
    X_test_noisy_s);

noisyScore = ...
    -noisyScore;

noisyResult = ...
    calculateMetrics( ...
    noisyScore, ...
    labels_test, ...
    svmThreshold);

fprintf( ...
    'Triuksmo lygis = %.2f\n', ...
    noiseLevel);

fprintf( ...
    'Recall su triuksmu = %.4f\n', ...
    noisyResult.recall);

fprintf( ...
    'Warnings/day su triuksmu = %.2f\n', ...
    noisyResult.warningsPerDay);

%% 41. Baigta

fprintf('\n');
fprintf('========================================\n');
fprintf('ANALIZE BAIGTA\n');
fprintf('========================================\n');


%% FUNKCIJOS


function y = sigmoid(x)

    x = max(min(x,50),-50);

    y = ...
        1 ./ (1 + exp(-x));

end


function score = baselineScore(X,W)

    signal = X(:,1);

    movingMean = ...
        movmean( ...
        signal, ...
        [W 0], ...
        'Endpoints', ...
        'shrink');

    movingStd = ...
        movstd( ...
        signal, ...
        [W 0], ...
        'Endpoints', ...
        'shrink');

    score = ...
        abs(signal - movingMean) ...
        ./ (movingStd + 1e-8);

end


function score = selectScoreDummy()
    score = [];
end


function threshold = selectThreshold( ...
    scores, ...
    labels, ...
    maxWarningsPerDay)

    sortedScores = ...
        sort(scores);

    N = ...
        length(sortedScores);

    numberOfCandidates = ...
        min(300,N);

    candidateIndex = ...
        round(linspace( ...
        1,N,numberOfCandidates));

    candidateIndex = ...
        unique(candidateIndex);

    thresholds = ...
        sortedScores(candidateIndex);

    bestRecall = -1;

    threshold = ...
        thresholds(end);

    for i = 1:length(thresholds)

        currentThreshold = ...
            thresholds(i);

        prediction = ...
            scores >= currentThreshold;

        warningsPerDay = ...
            sum(prediction) ...
            / length(prediction) * 96;

        if warningsPerDay <= ...
                maxWarningsPerDay

            TP = sum( ...
                prediction == 1 & ...
                labels == 1);

            FN = sum( ...
                prediction == 0 & ...
                labels == 1);

            if TP + FN > 0

                recall = ...
                    TP / ...
                    (TP + FN);

            else

                recall = 0;

            end

            if recall > bestRecall

                bestRecall = recall;

                threshold = ...
                    currentThreshold;

            end

        end

    end

end


function metrics = calculateMetrics( ...
    scores, ...
    labels, ...
    threshold)

    prediction = ...
        scores >= threshold;

    TP = sum( ...
        prediction == 1 & ...
        labels == 1);

    FN = sum( ...
        prediction == 0 & ...
        labels == 1);

    if TP + FN > 0

        recall = ...
            TP / ...
            (TP + FN);

    else

        recall = 0;

    end

    numberOfDays = ...
        length(scores) / 96;

    warningsPerDay = ...
        sum(prediction) / ...
        numberOfDays;

    metrics.recall = ...
        recall;

    metrics.warningsPerDay = ...
        warningsPerDay;

    metrics.warnings = ...
        sum(prediction);

end


function stability = calculateStability( ...
    scores, ...
    threshold)

    prediction = ...
        scores >= threshold;

    samplesPerDay = 96;

    numberOfDays = ...
        floor(length(prediction) / ...
        samplesPerDay);

    if numberOfDays < 2

        stability = 0;

        return;

    end

    dailyWarnings = ...
        zeros(numberOfDays,1);

    for i = 1:numberOfDays

        firstIndex = ...
            (i-1) * samplesPerDay + 1;

        lastIndex = ...
            i * samplesPerDay;

        dailyWarnings(i) = ...
            sum(prediction( ...
            firstIndex:lastIndex));

    end

    stability = ...
        std(dailyWarnings);

end


function [X_new,labels] = ...
    injectAnomalies(X,rate)

    X_new = X;

    N = ...
        size(X,1);

    anomalyCount = ...
        max(1,floor(N * rate));

    indices = ...
        randperm(N,anomalyCount);

    labels = ...
        zeros(N,1);

    for i = 1:length(indices)

        index = ...
            indices(i);

        anomalyType = ...
            mod(i-1,3);

        if anomalyType == 0

            % Didelis vartojimo padidejimas

            X_new(index,1) = ...
                X_new(index,1) * 3;

        elseif anomalyType == 1

            % Didelis vartojimo sumazejimas

            X_new(index,1) = ...
                X_new(index,1) * 0.1;

        else

            % Vidutinis vartojimo pokytis

            X_new(index,1) = ...
                X_new(index,1) * 1.8;

        end

        labels(index) = 1;

    end

end